version: "3"

services:
  rng:
    build: ./rng
    expose:
      - 80
    scale: 2

  rng_loadbalancer:
    build: ./rng_loadbalancer
    depends_on:
      - rng
    ports:
      - "4000:4000"

  particles:
    build: ./particles
    ports:
      - "80:80"
    container_name: particles
