version: "3"

services:
  rng:
    build: ./rng
    expose:
      - 80
    ports:
      - 8888:80
    container_name: rng

  particles:
    build: ./particles
    ports:
      - "80:80"
    container_name: particle
