version: "3"

services:
  rng:
    build: ./rng
    environment:
      - WEB_CONCURRENCY=1
    expose:
      - 80
    deploy:
      replicas: 4
    cpus: 0.15

  rng_loadbalancer:
    build: ./rng_loadbalancer
    depends_on:
      - rng
    ports:
      - "4000:4000"
    container_name: rng_loadbalancer

  particles:
    build: ./particles
    environment:
      - WEB_CONCURRENCY=1
    expose:
      - 80
    depends_on:
      - rng_loadbalancer
    # container_name: particles
    cpus: 0.2
    deploy:
      replicas: 4

  data_agg:
    build: ./data_agg
    environment:
      - WEB_CONCURRENCY=1
    ports:
      - "8080:80"
    depends_on:
      - particles
    container_name: data_agg

  data_agg_redis:
    build: ./data_agg_redis
    expose:
      - 6379
    container_name: data_agg_redis

  notebook:
    build: ./notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks
    working_dir: /notebooks
    environment:
      JUPYTER_TOKEN: admin
    container_name: notebook
