version: "3"

services:
  rng:
    build: ./rng
    expose:
      - 80
    environment:
      - WEB_CONCURRENCY=1
    scale: 1

  rng_loadbalancer:
    build: ./rng_loadbalancer
    depends_on:
      - rng
    ports:
      - "4000:4000"
    container_name: rng_loadbalancer

  particles:
    build: ./particles
    expose:
      - 80
    depends_on:
      - rng_loadbalancer
    scale: 5

  data_agg:
    build: ./data_agg
    ports:
      - "8080:80"
    depends_on:
      - particles
    # environment:
    #   - WEB_CONCURRENCY=1
    container_name: data_agg
