version: "3"

services:
  rng:
    build: ./rng
    environment:
      - WEB_CONCURRENCY=1
      - TIMEOUT=3600
    expose:
      - 80
    deploy:
      replicas: 1
    cpus: 0.2

  rng_loadbalancer:
    build: ./rng_loadbalancer
    depends_on:
      - rng
    ports:
      - "4000:4000"
    container_name: rng_loadbalancer
    healthcheck:
      test: curl --fail http://rng_loadbalancer:4000/lcg_params/ || exit 1
      interval: 2s
      retries: 10

  particle:
    build: ./particle
    depends_on:
      rng_loadbalancer:
        condition: service_healthy
      redis_store:
        condition: service_started
    cpus: 0.15
    deploy:
      replicas: 4

  data_agg:
    build: ./data_agg
    environment:
      - WEB_CONCURRENCY=1
    ports:
      - "8080:80"
    depends_on:
      - redis_store
    container_name: data_agg

  redis_store:
    build: ./redis_store
    expose:
      - 6379
    container_name: redis_store

  jupyterlab:
    build: ./jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ../notebooks:/notebooks
    working_dir: /notebooks
    environment:
      JUPYTER_TOKEN: admin
    container_name: jupyterlab
